### PR TITLE
Lead changes

### PR DESCRIPTION
**Pull request by respinoza**
This PR adds two API calls.
Lead changes (http://developers.marketo.com/documentation/rest/get-lead-changes/)
Pagination Token (http://developers.marketo.com/documentation/rest/get-paging-token/)

Notice that the pagination token is needed for the lead changes call.

### CODE REVIEW

**Comment by respinoza** [comment]
@dchesterton any comments on this PR? Thank you.

**Comment by nurikabe** [comment]
+1

**Comment by dchesterton** [comment]
Sorry for the delay with this, it's merged now.

**Comment by respinoza** [comment]
No problem, thank you.

**Pull request merged**
